# server配置
server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M  #session过期时间 60M 一小时

# websocket端口
ws:
  port: 5051

# logback
log:
  root:
    # 日志级别
    level: debug
# 数据存储位置
project:
  folder: D:/MyChat

# 超级管理员id
admin:
  emails: admin@qq.com,test01@qq.com

# 是否开发环境
dev: false

# 常量
contants:
  REDIS_KEY_CHECK_CODE: "myChat:checkCode:"
  REDIS_KEY_USER_HEARTBEAT: "myChat:user:heartbeat:"
  REDIS_KEY_USER_TOKEN: "myChat:user:token:"
  REDIS_KEY_USER_TOKEN_USERID: "myChat:user:token:userid:"
  REDIS_KEY_USER_CONTACT: "myChat:user:contact:"
  REDIS_KEY_SYS_SETTING: "myChat:sys:setting"
  REDIS_TIME_HEART_BEAT_EXPIRES: 6
  TIME_SECOND_1MIN: 60
  TIME_SECOND_1HOUR: 3600
  TIME_SECOND_1Day: 86400
  TIME_MILLISECONDS_1DAY: 86400000
  LENGTH_20: 20
  APP_NAME: "MyChatSetup"
  FILE_FOLDER_FILE: "file/"
  FILE_FOLDER_APP: "app/"
  FILE_FOLDER_AVATAR_NAME: "avatar/"
  PNG_SUFFIX: ".png"
  EXE_SUFFIX: ".exe"
  IMAGE_SUFFIX_LIST: .jpeg,.jpg,.png,.gif,.bmp,.webp
  VIDEO_SUFFIX_LIST: .mp4,.avi,.rmvb,.mkv,.mov,.webp
  COVER_PNG_SUFFIX: "_cover.png"
  APPLY_INFO_TEMPLATE: "我是%s"


spring:
  web:
    resources:
      # 禁用静态资源的自动映射
      add-mappings: false
  mvc:
    # 当请求的handler不存在时，直接抛异常
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      # 限制上传文件大小
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    druid:
      url: jdbc:mysql:///mychat?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Sa123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    # hikari连接池配置
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    # redis配置
    redis:
      database: 0
      host: 123.56.201.207
      port: 6379
      password: Wyz8472SWaz45wr
      jedis:
        pool:
          # 连接池最大连接数（负值表示无限制）
          max-active: 20
          # 连接池最大阻塞等待时间（负值表示无限制）
          max-wait: -1
          # 连接池中最大空闲连接
          max-idle: 10
          # 连接池中最小空闲连接
          min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 2000
